name: cardd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
    assets: 
    - C:/Users/jmorr/OneDrive/Desktop/repo/cardgame/cardd/lib/assets/images/image1.png
    - C:/Users/jmorr/OneDrive/Desktop/repo/cardgame/cardd/lib/assets/images/image2.png
    - C:/Users/jmorr/OneDrive/Desktop/repo/cardgame/cardd/lib/assets/images/image3.png
    - C:/Users/jmorr/OneDrive/Desktop/repo/cardgame/cardd/lib/assets/images/image4.png
    - C:/Users/jmorr/OneDrive/Desktop/repo/cardgame/cardd/lib/assets/images/back.png